
modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
modId = "smporigins"
version = "0.7"
displayName = "SMPorigins"
authors = "PeregrinKnight"
description = '''
This mod is derived from the SMP Origins Datapack
'''
