
modLoader="javafml"
loaderVersion="[36,)"
license="Public Domain"

[[mods]]
modId="collectionorigins1"
version="2.0"
displayName="Imperium Origins Collection 1"
logoFile="examplemod.png"
authors="Commander_Why"
description='''
This is a collection of 5 of the solo origin mods I have published.
'''
