
modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
modId = "libra"
version = "0.4"
displayName = "Libra"
authors = "Jasel Umena"
description = '''
Adds Umena's Libra & Canine origins. Requires Origins 1.17 or higher to work.
'''
